data:extend({
  {
    type = "string-setting",
    name = "auto-loader-chest-cost",
    setting_type = "startup",
    default_value = "normal",
    allowed_values = { "cheat", "easy", "normal", "expensive" },
    order = "a",
  },
  {
    type = "string-setting",
    name = "auto-loader-chest-availability",
    setting_type = "startup",
    default_value = "normal",
    allowed_values = { "cheat", "easy", "normal", "hard" },
    order = "b",
  },
  {
    type = "int-setting",
    name = "auto-loader-chest-batch-size",
    setting_type = "runtime-global",
    default_value = 10,
    minimum_value = 1,
    maximum_value = 1000,
    order = "a",
  },
  {
    type = "int-setting",
    name = "auto-loader-chest-tick-interval",
    setting_type = "runtime-global",
    default_value = 1,
    minimum_value = 1,
    maximum_value = 600,
    order = "b",
  },
  {
    type = "int-setting",
    name = "auto-loader-chest-default-max-insert",
    setting_type = "runtime-global",
    default_value = 10,
    minimum_value = 0,
    maximum_value = 100000,
    order = "c",
  },
  {
    type = "string-setting",
    name = "auto-loader-chest-insert-overrides",
    setting_type = "runtime-global",
    default_value = "nuclear-fuel=1,uranium-fuel-cell=1",
    allow_blank = true,
    order = "d",
  },
})
