data:extend({
  {
    type = "string-setting",
    name = "auto-loader-chest-cost",
    setting_type = "startup",
    default_value = "normal",
    allowed_values = { "cheat", "easy", "normal", "expensive" },
    order = "a",
  },
  {
    type = "string-setting",
    name = "auto-loader-chest-availability",
    setting_type = "startup",
    default_value = "normal",
    allowed_values = { "cheat", "easy", "normal", "hard" },
    order = "b",
  },
  {
    type = "int-setting",
    name = "auto-loader-chest-batch-size",
    setting_type = "runtime-global",
    default_value = 10,
    minimum_value = 1,
    maximum_value = 1000,
    order = "a",
  },
  {
    type = "int-setting",
    name = "auto-loader-chest-tick-interval",
    setting_type = "runtime-global",
    default_value = 1,
    minimum_value = 1,
    maximum_value = 600,
    order = "b",
  },
  {
    type = "int-setting",
    name = "auto-loader-chest-max-fill",
    setting_type = "runtime-global",
    default_value = 10,
    minimum_value = 1,
    maximum_value = 1000,
    order = "c",
  },
  {
    type = "string-setting",
    name = "auto-loader-chest-default-fuel-strategy",
    setting_type = "runtime-global",
    default_value = "lowest_quality_first",
    allowed_values = { "highest_quality_first", "lowest_quality_first", "highest_count_first", "lowest_count_first" },
    order = "d",
  },
  {
    type = "string-setting",
    name = "auto-loader-chest-default-ammo-strategy",
    setting_type = "runtime-global",
    default_value = "highest_quality_first",
    allowed_values = { "highest_quality_first", "lowest_quality_first", "highest_count_first", "lowest_count_first" },
    order = "e",
  },
})
